/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutComponent: typeof import('./src/components/AboutComponent.vue')['default']
    AchievementsComponent: typeof import('./src/components/AchievementsComponent.vue')['default']
    AvailabilityComponent: typeof import('./src/components/AvailabilityComponent.vue')['default']
    CalendarComponent: typeof import('./src/components/kits/CalendarComponent.vue')['default']
    ClientsComponent: typeof import('./src/components/ClientsComponent.vue')['default']
    ConditionComponent: typeof import('./src/components/kits/ConditionComponent.vue')['default']
    GalleryComponent: typeof import('./src/components/GalleryComponent.vue')['default']
    ImageComponent: typeof import('./src/components/kits/ImageComponent.vue')['default']
    ReviewCard: typeof import('./src/components/kits/ReviewCard.vue')['default']
    ServicesComponent: typeof import('./src/components/ServicesComponent.vue')['default']
    SwipperComponent: typeof import('./src/components/kits/SwipperComponent.vue')['default']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
    WelcomeComponent: typeof import('./src/components/WelcomeComponent.vue')['default']
  }
}
